name: Laravel Code Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coding-standart:
    uses: beyondCRUD/.github/.github/workflows/coding-standards.yml@main
  tests:
    uses: beyondCRUD/.github/.github/workflows/laravel-tests.yml@main
